name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch, change if you use another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Use a compatible Node.js version

    - name: Install dependencies
      run: |
        npm install

    - name: Build the app
      run: |
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # The directory containing the built files
        cname: "weeb-er.github.io"  # If you have a custom domain, otherwise omit this line
        target_branch: gh-pages  # Ensure this is set to the branch you want to deploy to (usually gh-pages)
        keep_files: true  # Optional, but can help with keeping the previous deploy files
